# pandas 数据分析

In [6]:
# 数据导入
import pandas as pd
import os

current_dir = os.path.dirname(os.getcwd())
file_path = os.path.join(current_dir, 'res', 'data', 'employees.csv')
df = pd.read_csv(file_path)
print(df.head(5), '\n', df.tail(5))

   employee_id first_name last_name     email  phone_number   job_id   salary  \
0          100     Steven      King     SKING  515.123.4567  AD_PRES  24000.0
1          101      N_ann   Kochhar  NKOCHHAR  515.123.4568    AD_VP  17000.0
2          102        Lex   De Haan   LDEHAAN  515.123.4569    AD_VP  17000.0
3          103  Alexander    Hunold   AHUNOLD  590.423.4567  IT_PROG   9000.0
4          104      Bruce     Ernst    BERNST  590.423.4568  IT_PROG   6000.0

   commission_pct  manager_id  department_id
0             NaN         NaN           90.0
1             NaN       100.0           90.0
2             NaN       100.0           90.0
3             NaN       102.0           60.0
4             NaN       103.0           60.0
      employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0

In [11]:
print(df.salary.mean())

df.to_csv(os.path.join(os.path.dirname(file_path), 'new.csv'))

6461.682242990654

In [23]:
# Json
file_path_1 = os.path.join(os.path.dirname(file_path), 'test.json')
df = pd.read_json(file_path_1)
print(type(df))
import json
with open(file_path_1) as f:
    data = json.load(f)


print(type(data))
df = pd.DataFrame(data['users'])
df

<class 'pandas.core.frame.DataFrame'>
<class 'dict'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

### 缺失值处理

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, None, pd.NA])
df = pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]])
print(s)
print('-'*20)
# 查看是否是缺失值
print(s.isna())
print('-'*20)

print(df)
print('-'*20)
print(df.isnull())

print(s.isna().sum(),df.isnull().sum(),sep='\n\n')

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
--------------------
0    False
1    False
2     True
3     True
4     True
dtype: bool
--------------------
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
--------------------
       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False
3

0    1
1    1
2    0
dtype: int64
0    1
1    2
dtype: object

In [ ]:
# 剔除缺失值
print(s)
print('-'*30)
print(s.dropna()) # 剔除缺失值那一行
print('-'*30)

print(df)
print('-'*30)
print(df.dropna(how='all')) # 所有值都是缺失值，删除这一行
print('-'*30)
print(df.dropna(thresh=3)) # 如果至少有n个值不是缺失值，就保留
print(df.dropna(axis=1)) # 剔除一整列的记录
# print(df.dropna(subset=['第1列'])) # 如果某列有缺失值则删除这一行

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
------------------------------
0    1
1    2
dtype: object
------------------------------
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
     0  1  2
1  2.0  3  5
   2
0  2
1  5
2  6

In [ ]:
# 填充缺失值
file_path_2 = os.path.join(os.path.dirname(file_path), 'weather_withna.csv')
df = pd.read_csv(file_path_2)
print(df.isna().sum(axis=0))
print(df.head())
print('-'*30)
print(df.fillna({'temp_max':20, 'wind':2.5}).tail()) # 使用字典填充后（看tail）
print(df.fillna(df[['wind']].mean()).tail()) # 使用统计值来填充

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64
         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain
------------------------------
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700000  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500000     rain
2     2012-01-03            0.8      11.7       7.2  2.300000     rain
3     2012-01-04           20.3      12.2       5.6  4.700000     rain
4     2012-01-05            1.3       8.9       2.8  6.100000     rain
...          ...            ...       ...       ...       ...      ...
1456  2015-12-27            NaN       NaN       NaN  3.242055      NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055      NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055      NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055      NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000     rain

[1461 rows x 6 columns]

In [55]:
print(df)
print('-'*30)
print(df.ffill().tail()) # 用前面数据添加 Ffill(F:font)
print(df.bfill().tail()) #

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            NaN       NaN       NaN   NaN      NaN
1457  2015-12-28            NaN       NaN       NaN   NaN      NaN
1458  2015-12-29            NaN       NaN       NaN   NaN      NaN
1459  2015-12-30            NaN       NaN       NaN   NaN      NaN
1460  2015-12-31           20.6      12.2       5.0   3.8     rain

[1461 rows x 6 columns]
------------------------------
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [56]:
import pandas as pd
data = {
    'name':['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age': [26,25,30,25,35,30],
    'city':['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

### 重复数据处理

In [64]:
print(df)
print('-'*30)
print(df.duplicated()) # 一整条记录都是一样的，标记为重复，返回True
print(df.drop_duplicates()) # 删除重复的 
print(df.drop_duplicates(subset=['name'])) # 根据指定列去重
df.drop_duplicates(subset=['name'], keep='last') # 保留最新出现的行

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA
------------------------------
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
4   jack   35   SF
    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

### 数据类型转换

In [69]:
file_path_3 = os.path.join(os.path.dirname(file_path), 'sleep.csv')
df = pd.read_csv(file_path_3)
df.head()
df.dtypes

person_id                    int64
gender                      object
age                          int64
occupation                  object
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                object
blood_pressure              object
heart_rate                   int64
daily_steps                  int64
sleep_disorder              object
dtype: object

In [74]:
df['age'] = df['age'].astype('int16')
df.dtypes
df['gender'] = df['gender'].astype('category')
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [76]:
df['is_male'] = df['gender'].map({'Female':True, 'Male':False})
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

In [ ]:
# 数据变形